# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  Configuration: 'Debug'
steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'ApnaBank/ApnaBank.sln'
    feedsToUse: 'select'
    configuration: 'Debug'
- task: MSBuild@1
  inputs:
    solution: 'ApnaBank/ApnaBank.sln'
    platform: AnyCPU
    configuration: 'Debug'
    clean: true